// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7mnmy6fKt9yh93CD-ZBFKTh3g3FKe0ws',
    appId: '1:463690646567:android:fcd4f27bc7725a02c07a02',
    messagingSenderId: '463690646567',
    projectId: 'pingmyride-16cbf',
    databaseURL: 'https://pingmyride-16cbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingmyride-16cbf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFBOWhTzZBbyxz5X8WWJfBwC2RXdKUPks',
    appId: '1:463690646567:ios:49db750426047000c07a02',
    messagingSenderId: '463690646567',
    projectId: 'pingmyride-16cbf',
    databaseURL: 'https://pingmyride-16cbf-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pingmyride-16cbf.firebasestorage.app',
    iosBundleId: 'com.example.driverapp',
  );
}
